// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jutierpdeipvgyinahyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1dGllcnBkZWlwdmd5aW5haHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTYwMzIsImV4cCI6MjA2NjE5MjAzMn0.vNjv6xWIHk-aCcIC1IEAo8uTcFpm7Rpbfoauz5OBt2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);